### ISSUE TITLE
Not an issue, just a question or two...

### ISSUE THREAD

**Issue by fblais** [lassekongo83/stajl-theme#3]
Hi Lasse.
Just wanted to ask if you plan to resume working on this theme someday please?

Also, do plan to do a dark version of the Plano theme please?

Best regards,
François

**Comment by lassekongo83** [comment]
I'm undecided about this theme at the moment. Also gtk-4.0 will soon arrive on many distros. Must familiarize myself with what's new. But it's not a high priority at the moment.

You can use an unsupported dark version of Plano if you set `$variant: 'light';` to  `dark` in `gtk.scss` and then reinstall the theme with meson/ninja.

**Comment by fblais** [comment]
Thanks I'll try that!

All the best!
François

**Comment by fblais** [comment]
Didn't work, sorry.
Reinstalled from scratch to be sure.
I understand it's unsupported so I won't bother you more with this.
